about:
  avatar: https://source.geniucker.top/avatar.webp
  name: "Geniucker"
  intro: "This is Geniucker's Blog"
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/geniucker', tip: 'GitHub' }
    - { class: 'iconfont icon-mail', link: 'mailto:me@geniucker.top', tip: 'Email' }
index:
  slogan:
    enable: true
    text: 欢迎来到我的博客~这里主要是技术笔记和随笔


favicon: https://source.geniucker.top/logo/favicon-32x32-next.png
navbar:
  blog_title: Geniucker's Blog
  menu:
    - { key: 'home', link: '/', icon: 'iconfont icon-home-fill' }
    - { key: 'archive', link: '/archives/', icon: 'iconfont icon-archive-fill' }
    - { key: 'category', link: '/categories/', icon: 'iconfont icon-category-fill' }
    - { key: 'tag', link: '/tags/', icon: 'iconfont icon-tags-fill' }
    - { key: 'links', link: '/links/', icon: 'iconfont icon-link-fill' }
    - { key: 'about', link: '/about/', icon: 'iconfont icon-user-fill' }


post:
  meta:
    # 作者，优先根据 front-matter 里 author 字段，其次是 hexo 配置中 author 值
    # Author, based on `author` field in front-matter, if not set, based on `author` value in hexo config
    author:
      enable: true

  # 在文章开头显示文章更新时间，该时间默认是 md 文件更新时间，可通过 front-matter 中 `updated` 手动指定（和 date 一样格式）
  # Update date is displayed at the beginning of the post. The default date is the update date of the md file, which can be manually specified by `updated` in front-matter (same format as date)
  updated:
    enable: true

    # 格式参照 ISO-8601 日期格式化
    # ISO-8601 date format
    # See: http://momentjs.cn/docs/#/parsing/string-format/
    date_format: "LL a"

    # 是否使用相对时间表示，比如："3 天前"
    # If true, it will be a relative time, such as: "3 days ago"
    relative: false

    # 提示标签类型
    # Note class
    # Options: default | primary | info | success | warning | danger | light
    note_class: info

  math:
    # 开启后文章默认可用，自定义页面如需使用，需在 Front-matter 中指定 `math: true`
    # If you want to use math on the custom page, you need to set `math: true` in Front-matter
    enable: true

    # 开启后，只有在文章 Front-matter 里指定 `math: true` 才会在文章页启动公式转换，以便在页面不包含公式时提高加载速度
    # If true, only set `math: true` in Front-matter will enable math, to load faster when the page does not contain math
    specific: true

    # Options: mathjax | katex
    engine: mathjax
  comments:
    enable: true
    type: giscus
giscus:
  repo: "Geniucker/blog-commnet"
  repo-id: "R_kgDOHodssA"
  category: "Announcements"
  category-id: "DIC_kwDOHodssM4CdRHE"
  mapping: "path"
  strict: "0"
  reactions-enabled: "1"
  emit-metadata: "0"
  theme: "preferred_color_scheme"
  lang: "en"
  loading: "lazy"



footer:
  statistics:
    enable: true
    source: "busuanzi"  # 可选 leancloud | busuanzi  根据自己需求选择
    pv_format: "总访问量 {} 次"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"


links:
  items:
    - {
      title: "cyc's notebook",
      intro: "花生瓜子八宝粥，编程建模GPT",
      link: "https://cyc-987.github.io/",
      avatar: "https://cyc-987.github.io/logo.jpeg"
    }
    - {
      title: "暮森の小屋",
      intro: "",
      link: "https://musanico.github.io/",
      avatar: "https://avatars.githubusercontent.com/u/108330876?s=400&u=0c5c811a193fd0dac9e46348ac2104dcea881654&v=4"
    }
  default_avatar: /img/avatar.png